/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sihle
 */
public class CustomerForm extends javax.swing.JFrame {
        DbConnect dbConnect;
    /**
     * Creates new form customerForm
     */
    public CustomerForm(DbConnect dbConnect) {
        initComponents();
        this.dbConnect = dbConnect;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNationalId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtCellphoneNumber = new javax.swing.JTextField();
        txtPhysicalAddress = new javax.swing.JTextField();
        txtNextOfKeen = new javax.swing.JTextField();
        txtRelationship = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Details");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sihle\\Downloads\\log.jpg")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setText("National ID");

        jLabel3.setText("Name");

        jLabel4.setText("Surname");

        jLabel5.setText("Gender");

        jLabel6.setText("Date of birth");

        jLabel7.setText("Email address");

        jLabel8.setText("Cellphone");

        jLabel9.setText("Physical address");

        jLabel10.setText("Next of keen");

        jLabel11.setText("Relationship");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        female.setText("Female");

        male.setText("Male");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNationalId)
                            .addComponent(txtName)
                            .addComponent(txtSurname)
                            .addComponent(txtDateOfBirth)
                            .addComponent(txtEmailAddress)
                            .addComponent(txtCellphoneNumber)
                            .addComponent(txtPhysicalAddress)
                            .addComponent(txtNextOfKeen)
                            .addComponent(txtRelationship)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(female)
                                .addGap(38, 38, 38)
                                .addComponent(male)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNationalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(female)
                    .addComponent(male))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCellphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPhysicalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNextOfKeen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("CUSTOMER DETAILS");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)))
                .addComponent(jButton3)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 772, 498);
    }// </editor-fold>//GEN-END:initComponents

    protected void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Customer c =new Customer();
         String Gend="";
         if(this.female.isSelected()){
             Gend="Female";
         }else if(this.male.isSelected()){
             Gend="Male";
         }
        if (!(this.txtNationalId.getText().isEmpty()&&this.txtName.getText().isEmpty()&&this.txtSurname.getText().isEmpty()
                &&this.txtDateOfBirth.getText().isEmpty() &&this.txtEmailAddress.getText().isEmpty()
                && this.txtCellphoneNumber.getText().isEmpty() &&this.txtPhysicalAddress.getText().isEmpty() &&this.txtNextOfKeen.getText().isEmpty()
                &&this.txtRelationship.getText().isEmpty()) && (this.female.isSelected() || this.male.isSelected())){
                       
                    c.setNationalId(this.txtNationalId.getText());
                    c.setName(this.txtName.getText());
                    c.setSurname(this.txtSurname.getText());
                    c.setGender(Gend);
                    c.setDateOfBirth(this.txtDateOfBirth.getText()); 
                    c.setEmailAddress(this.txtEmailAddress.getText());
                    c.setCellphoneNumber(this.txtCellphoneNumber.getText());
                    c.setPhysicalAddress(this.txtPhysicalAddress.getText());
                    c.setNextOfKeen(this.txtNextOfKeen.getText());
                    c.setRelationship(this.txtRelationship.getText());                    
                    c.AddCustomerDetails(dbConnect);
                    new ComplianceForm().setVisible(true);
                    this.dispose ();
        
             }          
          else
                {
                    JOptionPane.showMessageDialog(rootPane, "fill all the information required before you add this customer");  
                }
       
                
    }//GEN-LAST:event_jButton1ActionPerformed

    protected void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Customer c = new Customer();
        DbConnect dbConnect = new DbConnect();
        if (!(this.txtNationalId.getText().isEmpty()))
        { 
            if (!(this.txtEmailAddress.getText().isEmpty()))
            {              
                c.setNationalId(this.txtNationalId.getText());
                c.setName(this.txtName.getText());
                c.setSurname(this.txtSurname.getText());
                c.setDateOfBirth(this.txtDateOfBirth.getText());
                c.setEmailAddress(this.txtEmailAddress.getText());
                c.setCellphoneNumber(this.txtCellphoneNumber.getText());
                c.setNextOfKeen(this.txtNextOfKeen.getText());
                c.setRelationship(this.txtRelationship.getText());        
                c.UpdateCustomer(dbConnect, this.txtNationalId.getText());
                new CustomerForm(dbConnect).setVisible(true);
                this.dispose ();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, " CHECK  customer before you update "); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, " CHECK  customer before you update "); 
        }                                        
                                       

    }//GEN-LAST:event_jButton2ActionPerformed

    protected void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Customer c = new Customer();

        if (!(this.txtNationalId.getText().isEmpty()))
            {
            if(!(this.txtName.getText().isEmpty()))
            {
                   c.setNationalId(this.txtNationalId.getText());
                   c.deleteCustomer();
                   Customer f= new Customer();
                   f.setNationalId(this.txtNationalId.getText());
                   f.deleteCustomer();
                   
                   txtNationalId.setText("");
                   txtName.setText("");
                   txtSurname.setText("");
                   txtDateOfBirth.setText("");
                   txtPhysicalAddress.setText("");
                   txtNextOfKeen.setText("");
                   txtRelationship.setText("");
                   txtCellphoneNumber.setText("");
                   if (c.getIsCustomerDeleted())
                   {              
                      new CustomerForm(dbConnect).setVisible(true);
                       this.dispose(); 
                   }
            }
            else
            {
               JOptionPane.showMessageDialog(rootPane, " CHECK customer you want to delete "); 
            }
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane, " CHECK customer you want to delete ");
        }    
                                 
                                                       

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:


        txtName.setText("");
        txtSurname.setText("");
        txtDateOfBirth.setText("");
        txtPhysicalAddress.setText("");
        txtNextOfKeen.setText("");
        txtRelationship.setText("");
        txtCellphoneNumber.setText("");
        txtEmailAddress.setText("");

        Customer c = new Customer();
      //  DbConnect dbConnect = new DbConnect();
        c.setNationalId(this.txtNationalId.getText());
        if (!(this.txtNationalId.getText().isEmpty()))
        {      
              try
              {
                   ResultSet rec = c.ViewIndividualCustomer(dbConnect, this.txtNationalId.getText());
                   while (rec.next())
                   {              
                       this.txtName.setText(rec.getString(2));
                       this.txtSurname.setText(rec.getString(3));
                       this.txtEmailAddress.setText(rec.getString(4));
                       this.txtDateOfBirth.setText(rec.getString(6));
                       this.txtPhysicalAddress.setText(rec.getString(7));
                       this.txtCellphoneNumber.setText(rec.getString(8));
                       this.txtNextOfKeen.setText(rec.getString(9));
                       this.txtRelationship.setText(rec.getString(10));
                                                   
                   }
                   
                   if (!(this.txtSurname.getText().isEmpty()))
                         {
                           jButton1.setEnabled(false);
                           jButton3.setEnabled(true);
                           jButton4.setEnabled(true);
                           
                         }
                   else
                         {
                             JOptionPane.showMessageDialog(rootPane, " this Customer does  not exist in the system. add him or her first");
                             jButton4.setEnabled(true);
                             jButton1.setEnabled(true);
                             jButton3.setEnabled(true);
                         }
               }   
               catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
                   
               }
        }
        else
        {
               JOptionPane.showMessageDialog(rootPane, "Make sure national ID is not empty");
        }  
                               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        DbConnect dbConnect = new DbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new CustomerForm(dbConnect).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField txtCellphoneNumber;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationalId;
    private javax.swing.JTextField txtNextOfKeen;
    private javax.swing.JTextField txtPhysicalAddress;
    private javax.swing.JTextField txtRelationship;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
